spring:
  application:
    name: data-crawler
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

crawler:
  schedule:
    enabled: true
    cron: 0 0 * * * *
  url:
    example1: http://example.com/data1
    example2: http://example.com/data2